@startuml
hide empty description

state "STATUS_STOPPED (0)" as Stopped
state "STATUS_WAITING (1)" as Waiting
state "STATUS_EXTRACTING (2)" as Extracting
state "STATUS_COMPLETE (3)" as Complete
state "STATUS_MANUAL (4)" as Manual

[*] --> Stopped : System Init

Stopped --> Waiting : CMD_DRUG_SETTING (CMD=1)
Complete --> Waiting : CMD_DRUG_SETTING (CMD=1)

Waiting --> Extracting : PUSH_PIN Button Pressed

Extracting --> Complete : Dosing Pump END

Complete --> Stopped : PUSH_PIN Button Pressed

Stopped --> Manual : MANUAL_PIN Button Pressed
Waiting --> Manual : MANUAL_PIN Button Pressed

Manual --> Stopped : MANUAL_PIN Button Released

@enduml