@startuml
title Dosing System State Diagram

state STATUS_STOPPED
state STATUS_WAITING
state STATUS_EXTRACTING
state STATUS_COMPLETE
state STATUS_MANUAL

[*] --> STATUS_STOPPED : 도징 시스템 구동
STATUS_STOPPED --> STATUS_WAITING : 약물 설정 명령(CMD)
STATUS_WAITING --> STATUS_EXTRACTING : 추출 버튼 누름
STATUS_EXTRACTING --> STATUS_EXTRACTING : 도징펌프 가동
STATUS_EXTRACTING --> STATUS_COMPLETE : 추출 용량 도달
STATUS_COMPLETE --> STATUS_STOPPED : LCD 내용 삭제

STATUS_STOPPED --> STATUS_MANUAL : 수동추출 버튼 누름
STATUS_MANUAL --> STATUS_STOPPED : 수동추출 버튼 해제

@enduml
